# Generated by Django 4.2.5 on 2023-10-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz3', '0002_alter_orders_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='add_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(),
        ),
    ]
